
export const COLORS = {
  EMERALD_DEEP: '#013220',
  EMERALD_VIBRANT: '#043927',
  GOLD_METALLIC: '#D4AF37',
  GOLD_LIGHT: '#F9E2AF',
  GOLD_DEEP: '#AA822A',
  WARM_WHITE: '#FFF9E3',
  NIGHT_SKY: '#01160d'
};

export const TREE_CONFIG = {
  PARTICLE_COUNT: 45000,
  ORNAMENT_COUNT: 320,
  TREE_HEIGHT: 12,
  TREE_RADIUS: 5,
  SCATTER_RADIUS: 18,
  TRANSITION_SPEED: 0.05,
};

export const ORNAMENT_TYPES = {
  BAUBLE: 'BAUBLE',
  GIFT: 'GIFT',
  LIGHT: 'LIGHT'
} as const;
